### ISSUE TITLE
Update documentation to define permissions required by action

### ISSUE THREAD

**Issue by iacabezasbaculima** [BedrockStreaming/pr-size-labeler#7]
The following permissions must be added to a GitHub Actions workflow:

```yaml
permissions:
  pull-requests: write
  issues: write
```

This will provide the default `GITHUB_TOKEN` permissions to work with issues and pull requests.

Currently, the GitHub REST API endpoint used to add a label is [shared by issues and pull requests](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#about-labels).

Therefore, the documentation on how to use the action should be updated as follows:

```yaml
name: 🏷 PR size labeler

on: [pull_request]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: BedrockStreaming/pr-size-labeler@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_files: .lock
```

References:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
